In [1]:
import pandas as pd

In [8]:
annotations = pd.read_csv("../sample_to_annotate_without duplicate.csv")
annotations

        ID                                              tweet  annotation
0    15430  If its the news, it must be true? No, its not....         NaN
1     8514         Covid is going to ruin Christmas this year         NaN
2      275   today is a big day just went over 300 twitter...         NaN
3    11283   my family is being so supportive today and ma...         NaN
4    16276  @pamparoni If they aren’t out yet just wait to...         NaN
..     ...                                                ...         ...
994   4992  We are an evolved people.. seriously, can we f...         NaN
995  18233                             i feel loved 0 message         NaN
996  11964   thanks pendot for all the lines being painted...         NaN
997   8156   essays and television and twitter and drinkin...         NaN
998  10266                               WTF is Tim Horton’s?         NaN

[999 rows x 3 columns]